### ISSUE TITLE
Forward on admin lobby refresh

### ISSUE THREAD

**Issue by error401de** [error401de/csgo-mapvote#20]
"Admin left lobby" warning is working if the admin fully closes the browser. On refresh, the participants get no warning but are forwarded to index only.

**Comment by acra5y** [comment]
possibly connected to https://developers.google.com/web/updates/2017/03/dialogs-policy
"If alert() is called from a background tab, the call returns immediately"
Since it's also not that nice I'll replace it with like the ones shown on page load
